title: Jekyll Auto-tooltips
remote_theme: pages-themes/cayman@v0.2.0

repository: RichDom2185/jekyll-auto-tooltips
markdown: kramdown

description: A GitHub Pages-compatible Jekyll add-on for easy tooltips syntax.

plugins:
  - jemoji
  - jekyll-remote-theme
